# docker-compose.production.yml
version: '3'

volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: leyrus/taski_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
  frontend:
    image: leyrus/taski_frontend  # Качаем с DockerHub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: leyrus/taski_gateway  # Качаем с DockerHub
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80
